POST http://localhost:9000/signup HTTP/1.1
Content-Type: application/json

{
    "email": "zeus@hotmail.com",
    "login": "  zeus",
    "password": "IlikemywomenlikeIlikemycandy",
    "phone": "+380995262039",
    "address": "Petefi St. 52, Kidyosh, Zakarpattya, Ukraine",
    "firstname": "Zeus",
    "lastname": "TheGreat"
}
###
POST http://localhost:9000/signin HTTP/1.1
Content-Type: application/json

{
    "login": "zeus",
    "password": "IlikemywomenlikeIlikemycandy"
}
###
POST http://localhost:9000/additem HTTP/1.1
Content-Type: application/json

{
    "name": "Plunger",
    "description": "A really basic plunger. Long lasting, sturdy construction. Slim design.",
    "price": 20,
    "category": ["Household Items", "Bathroom"],
    "technicalDetails": {
        "Height": "30cm",
        "Weight": "0.8kg",
        "Diameter": "10cm"
    }
}
###
PATCH http://localhost:9000/addfavorite HTTP/1.1
Cookie: connect.sid=s%3AAE7tthRwI6-cTNeGAyzaWkA8AjvMQS0W.SyyD4ZiA%2FrjvaMuLZwg6KrMtZnTwkrQOygTd7vufuhE
Content-Type: application/json

{
    "itemID": "62d2dcd3ab2515f788a53702"
}
###
GET http://localhost:9000/ HTTP/1.1
Content-Type: text/plain