POST http://localhost:9000/signUp HTTP/1.1
Content-Type: application/json

{
    "email": "zeus@hotmail.com",
    "login": "  zeus",
    "password": "IlikemywomenlikeIlikemycandy"
}
###
POST http://localhost:9000/login HTTP/1.1
Content-Type: application/json

{
    "login": "zeus",
    "password": "IlikemywomenlikeIlikemycandy"
}
###
