import mongoose, { Schema } from "mongoose";

const userSchema = new Schema ({
    email: {
        type: String,
        unique: true
    },
    login: {
        type: String,
        unique: true
    },
    phone: {
        type: String,
        unique: true
    },
    passwordHashed: String,
    firstname: String,
    lastname: String,
    address: String,
    favorites: [{ 
        type: mongoose.SchemaTypes.ObjectId,
        ref: "Item"
    }], 

    // Autogenerated
    createdAt: {
        type: Date,
        default: () => Date.now()
    }
});

export const User = mongoose.model("User", userSchema);